language: java
cache:
  directories:
  - $HOME/.m2
jdk:
- oraclejdk8
sudo: required
services:
- docker
notifications:
  slack:
    secure: HAkVJBgThf2WBBz7LQtf+aRQd41sWNibfNWgjLMcMFk0wuTs3RDkE8KK0Jxe5MRmdg2GGU6LLoeD5miRdsgQ15gpAKYgy8S8vM6MYN15uk5Ky1kNvjeSICIxxdjDPKBYyU5sx/2KtqZcNQNsTwHUmF3Tw5V5dOCUYlQ3KrOSlck6j80sPs+McVyvma2uN1ewL7qDSf4AHOW7yycxXCZeHJvwtyPO9AT9HKOerDi/cu9PewpGNd6KW2WmKj+1SkQnEi3wYcD673ZyV3OXxorGUCPzA/Sen2dixJ2ONqc4EosF5mPnTFXwdWTAkvY4u8c5xonCcNrgkzuz6Hew0VAs9ozj6A3KULt6ZLEeKmTE8JB5GA10vdf+w9R7YC2CTjLY1SUrtHNbjKgV7VhKcqZ1oa0cX0B/HpxmfYQlyBU1LGLXfuSsbg3DMVwWP8qCmNHSD9qhsU+xgSAXpkP3v7vWbJpF/H0q+LC0UicZez5kh62xjR1RcEioWjKgdMOw4aSOnYH7Js8qLyiueeB5uCSUOZDlZ/QRg05wNvigyDHJrBk6EUhlgSHwpCVQ4ihM3YAvrwZNvHQE8EmsGvj49aGKDqF7fteiSEEdRyQq8eXC17NQnj4qpv2IhtdPquUVdZ/pM0wRlXdKPoPpXGy0mp/KJ1y9oSiqaYoGRhp1qOuivkQ=
  email:
  - anthony.denecheau@gmail.com
  on_success: always
  on_failure: always
env:
  global:
  - secure: GaTlLclC3iBX3xeOEEqP5EMzBn01veyFlArCDQl6BML5fHGsqljidvVvfFlMJIXfek5M1qUuoBhOHoFly1jFmJ31tXMfTyXuYXSa6J7Bb0Gt4bBtLP5rjOhtUAQIAU3Gz4mx9QGkSO6oB4lv9eBraqZCc7m3MquIazXtbAgMROr/bLgX1Tv9zNRrzKgwLKVfG3HCk4DuBSqZGGMSd8Mp6Mp9d3SK6Ba1oiS3tAgUvyYkfU3ZicYhnbsNS+aR6SP5PiWku/s9YHDuSTbLF9+V03VZMiMZYEkuqxcHd3SvdiaJPIbdN1iCii49DEFoKKMqKoBfcJNPyd8UkkkPhxSpZlwD61ApDkNPZaEC7lqaP2sQoRgdtT5kc+OeHcShLbEuLJIhCfoyIROZQC5Pb8pGZixNErA/8kewXpHfXdFrzl3m0W4q1ezN8S/WmD9Y7cBa+cY+YhlicknZSrlueGGtdQ7f/uLQfZ6f/iX0gXCnuG7/BX2JUPX/j0D6LD4Cyfi+mFhIfERBw4FqawrQ8opkuo+RqtVywvxf0FHUmDMK5fbiXSD2ZCa+Byo7D7BHtBoMlH79YWiu8fQaOXWld5UyWWYATBMtXG4p+jJfaA4Q+eAv4nLn2VR74iuu1yKVhIwwJwB6VeUrSv0wKHsBZ5bTxCHTmLOUm/rRbB5UX5iLUtI=
  - secure: X+ml0dwrZQCyhkav8wJp79YxxsqTY+RTsML9clAnt61SsQj7FfU5plVwDSxsev17ASA62oFhT06e7FbqDWhjDxGPj0oA7KbTPRXBZlbOkPDvIPZqHEu82lhjsZiH677F8OpXBjfmMERVBGmxbAAd5T08JlbruQ03BoXuzbJBY0gSFCq6KmdB52aT382yUGixLUSCu/Jvr+1innodC87MttS3I/wWdDYGV5s0gEdJ/79IpjY/2ckQJJlfOk500O5kCHDTK9E/xhsmT9Hm93WV3+nePwS9IeFAI7WZziSiOJV3bYhyWV69hqX2JxqLac6dPwyrjlF9O+rlRtEByynb5uN6OmHh96cdzbs26MPl1E67CJcPOu55uKPK5kqo52Ssi4ew6yrnbgBQBE3lNI0XJ6zJsdR7byYOc1Mp/IhFlhnAuJdPCMJDlQ/SjASrpUvs/VCd580kOfrwZIBIUfGR8/Nr4hI3hoWNkI8P0T8VqCY5EltR0KY5Jl9hVJH6CypmAtpxleWoPnl8h+G9Zxdxlv7YkR2zO3JpFjv67Pft/euuHnrnGvpEM/28M+gYplL2pFhCY1JeKtSl463MgHL64YXInf7e1zC1UeC7n+1vnj2kG/Pa9QfpcWZAaHVA9UQkndlylAGw4ZNZIYnemiMBV2JgieLbNch/vKyH/CGoZmE=
  matrix:
  - SCC_DOCKER_IMAGE=anthonydenecheau/scc-eurekasvr:version1.0
script:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- mvn clean package docker:build
- docker push $SCC_DOCKER_IMAGE
