language: java
cache:
  directories:
  - $HOME/.m2
jdk:
- oraclejdk8
sudo: required
services:
- docker
notifications:
  slack:
    secure: IXtR0NPXOjVMlhDuEZjhdL4MpvPWNrLEab9iSOpz+uF6/+GQoi0nzLtFNzfT4WQAmvADLORatw0ojBkAyYfzHFK8I39s53noy1iskSWm1BXPLcbURgrIzLaSCJiE93dpCWNWWOTW6ReRrtLKOtjZpeOIWs70IjCDXt4h+2W5BTCUsbUtf9J+Ps2UxwQ2sh40Ieevfyc7j6JLuKTu5d/a4Lg0sH+RiEYNKB1lTIcRrgWL2oghxVBIzKLR88ljSlRK+sX/Rfg4XaDz5QyvLm6feeqUrvkJ5xTU4YAEdnZ9oCP3cYvv9+/5gK8jmdRBdqfS2T0W5rcAc6sGrecaYurHm0mHhXfjMdmUBP0TzeSlF/sEoA/LduJBvmwszsPmatdKlN7ft812+c7ut2Bm8OTQEQBq7yK+z4up7O1Cg9z5LUXrMa/K+/MlWwq9RH6QbkrpOZOB6cioXSNt5TQNVLM9koIKiB0sLhwkCEYHIcea3wco1sxkRyHg33R6O3z5D8BE2cXBKTcSVqkJulYgTU95eXLVBHU/HVuCad7mJ34lBssgHmrtoG7BdWw/3LwiC8UlUw8eERyer9378U2MIP9ZVg/p041T/HP0sU8kXLx2Y3cE7auf//g4A2QtmrghEliWRHuGhCjX92Ehnm/WYzorOwpBTe+io4G7DJHtZFBFeD8=
  email:
  - anthony.denecheau@gmail.com
  on_success: always
  on_failure: always
env:
  global:
  - secure: M6TGGeDl2HJJQ6PxnxwWDTs0Cc6kNA4LhxYt+0z+cTouFrmc9fe+uu3SFzjU5odIVfa12sCOKOy2Fm6Gjfsicz3D3BnlVkrocwY9nzX4vIF4PlM+ptTd8Wkm0A4/clTOOGERglp2jPW1rtyL2XzcTW3Sam5bBmoHThXdiw234RtilGZTw8fYlcCuDGSz5MnLowtYrIKzhM8ltiBUq5El1YYqLrMtuJlolEd7TGwjcG8Fg2lT9GmI5shIcd5dwUjvoGhKkzdr6X+GuWnGG24JVET4eImdVuETsHRqxJvVwQgqkJXHayGLwMOFtA0I/95un16RTduf+j1L5RbGYL+hf0zcBZmgHFcrqnj9mhZkfXwcLiYdJ18T8bRpU1a0F+o4KKRBXDHH0bwYaSASabKVtWf5tP3N/SxP43IryX1ht9TkXvMBJAMAaszQcaeUoS9KnSzbPNikfzDEJ5kKbJfrzZV8jyed8MomBaKf/U7wkOUha1SWC4ucIL9XtY7vxT+BWX0qGnx7mQ6ZOf3uhSyforCsqbJfa60MRXJXXNT9TvVdaFs9c1fjmdBN3IXaJlXkAuwdkIHvS3Ov5NKp7PRUgcp1P24xe5/tLBi9+7Wq9uOL6lZHy682C41eTX1TorPFiYxrIYF16YqJEY35IJOnJ1AveG1dO/qjMxDhgmtj+8s=
  - secure: 0L3YU6j4TngMEAobU5c4qdLpI8cxbS3VERDIikroAcZ9BnejsPTj8DdxUPoJOr786Ms1G6DdYrbW6ec/dhpfoxzPbAmWK8OAqqxYtxmEqKMH9c5fDOk917Wvgrrk+j9Lb+DO2GaOB910UP6JuDEqQQ9yzaAssRWA6ZzG99GQLQAFW3AZZdpkyo10laU+3Q4K3PlN9m/Hih+agbTm0ubJjirLE1KpAosTY6zAbam1QKXqpt0pwdHxQdrbEIlwfG5YFTPr/IgH42GydXOm3jsjt5ksd7C+lwiVs32SCIKSHYz3LfU7J0HGByRpYbhPDWmn7gD6uJO0xuVdeV6E9lIZPa9evOU2JloixI0BfYXBxxHAnxR/BK74OAsfgo3yfd14pN7Pb3ZGCHP0Yk9WxmHZADZG9UyUmR9hb5y5xnRwJ4HLA0iA0ZE6AalAumsW+Qklheoj1HKCPea0pEIG4oUH5tkqi5XFFN26+AYAUcmTwcS/m/l20u5XSWcXt/yknBE6ydmU+tcqaeO61UXqy0S+8SfXUUMU5X5v6pGl7XmkXlrMDlpBQWxuZs+/ScAI9k5uxKFIXSHyjcO+1Rc87V7pkdeiZQeef95XfcgeWK2mdfdqglQsqrPlRh7LufnL02hKZ7Edzu5iPV9lZvabPiix5vM7xbnfwll6fGyFeRQoPmo=
  matrix:
  - SCC_DOCKER_IMAGE=anthonydenecheau/scc-eurekasvr:version1.0
script:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- mvn clean package docker:build
- docker push $SCC_DOCKER_IMAGE